scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']  # Адрес вашего Express-приложения

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']